Update dependencies & npm scripts
lelandrichardson/redux-pack pull request #74
Opened 2019-02-28 08:38 UTC by Robertmw

- [x] Update dependencies versions;
- [x] Fix npm warnings about npm scripts & peer dependencies;
- [x] Replace `react-native` with `metro-react-native-babel-preset`.

2019-02-28 17:10 UTC, ljharb requested changes
Given that the only change here that would require publishing is the Babel preset (the deps are already included by the semver range) I’m a bit confused about the urgency here. What’s the change in the Babel preset solving?

2019-02-28 17:10 UTC, ljharb commented on package-lock.json
> +{
Please remove this file; only apps should have lockfiles.

2019-02-28 17:10 UTC, ljharb commented on package.json
> +    "prepare": "npm run build",
please keep this as “prepublish”

2019-03-01 09:25 UTC, Robertmw commented
Hey, thanks for the review, I will make the changes today.

And sorry if I stress you or rush you, i don't mean to. I use this library in a project that is strict about dependency vulnerabilities (`npm audit`) hence the updated NPM package I made... And I cannot use the package as git dependency due to some project issues.

2019-03-01 17:56 UTC, ljharb commented
@Robertmw in that case you can update the transitive dependencies in your lockfile using `npm audit fix` with no downstream changes required.

2019-03-01 17:57 UTC, ljharb commented
Is `npm test` passing locally for you?

2019-03-01 19:26 UTC, Robertmw commented
Fixed the `npm test` as well. I also added `package-lock.json` in `.gitignore`

2019-03-01 19:26 UTC, ljharb commented on .gitignore
> +package-lock.json
let’s also add `package-lock=false` to `.npmrc`

2019-03-01 19:29 UTC, ljharb commented on .gitignore
> -package-lock.json
to clarify; it should be here also.

2019-03-01 19:31 UTC, Robertmw commented
This was the hardest PR in 2019 man.. 🤣

2020-05-29 20:12 UTC, closed without merging